apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-controller-sa
  namespace: kaggle-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-controller-role
  namespace: kaggle-agent
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-controller-rolebinding
  namespace: kaggle-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-controller-role
subjects:
  - kind: ServiceAccount
    name: job-controller-sa
    namespace: kaggle-agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-controller
  namespace: kaggle-agent
  labels:
    app: job-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-controller
  template:
    metadata:
      labels:
        app: job-controller
    spec:
      serviceAccountName: job-controller-sa
      containers:
      - name: controller
        image: kaggle-agent/controller:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: DATABASE_URL
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AGENT_IMAGE
          value: "kaggle-agent/agent:latest"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 512Mi
        volumeMounts:
        - name: shared-storage
          mountPath: /shared
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: submissions-storage

